DEV_DB_USERNAME: 'coupons'
DEV_DB_PASSWORD: 'coupons'

TEST_DB_USERNAME: 'coupons'
TEST_DB_PASSWORD: 'coupons'

DB_USERNAME: 'coupons'
DB_PASSWORD: 'coupons'

EXCHANGE_SERVER_ADDRESS: 'localhost'
EXCHANGE_SERVER_PORT: '5672'

JWT_SECRET: 'shhhhhh'
RAILS_SERVE_STATIC_FILES: 'true'
DB_HOST: 'localhost'
HOSTS: 'localhost'

